files:
  - source: app/Language/En/messages.php
    translation: /www/app/Language/%two_letters_code%/messages.php
  - source: www/app/Templates/Default/Assets/js/languages/En.json
    translation: www/app/Templates/Default/Assets/js/languages/%two_letters_code%.json
