files:
  - source: app/Language/En/messages.php
    translation: /www/app/Language/%two_letters_code%/messages.php
  - source: app/Language/En/frontend.php
    translation: /www/app/Language/%two_letters_code%/frontend.php
